const StateData = [
    {
        stateName: "Alabama",
        abbreviation: "AL",
        shippingFee: 9.99,
        publishingFee: 30.00,
        stateExpediteFee: 28.00,
        correspondentFee: 100.00,
        proofOfPublication: 208.00,
        recordingFee: 375.99,
        total: 375.99 // Sum of all fees
    },
    {
        stateName: "Alaska",
        abbreviation: "AK",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 250.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 259.99 // Sum of all fees
    },
    {
        stateName: "Arizona",
        abbreviation: "AZ",
        shippingFee: 9.99,
        publishingFee: 150.00,
        stateExpediteFee: 35.00,
        correspondentFee: 50.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 244.99 // Sum of all fees
    },
    {
        stateName: "Arkansas",
        abbreviation: "AR",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 45.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 54.99 // Sum of all fees
    },
    {
        stateName: "California",
        abbreviation: "CA",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 20.00,
        proofOfPublication: 70.00,
        recordingFee: 0.00,
        total: 99.99 // Sum of all fees
    },
    {
        stateName: "Colorado",
        abbreviation: "CO",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 50.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 59.99 // Sum of all fees
    },
    {
        stateName: "Connecticut",
        abbreviation: "CT",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 120.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 129.99 // Sum of all fees
    },
    {
        stateName: "Delaware",
        abbreviation: "DE",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 110.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 119.99 // Sum of all fees
    },
    {
        stateName: "District Of Columbia",
        abbreviation: "DC",
        shippingFee: 9.99,
        publishingFee: 50.00,
        stateExpediteFee: 0.00,
        correspondentFee: 99.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 158.99 // Sum of all fees
    },
    {
        stateName: "Florida",
        abbreviation: "FL",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 125.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 134.99 // Sum of all fees
    },
    {
        stateName: "Georgia",
        abbreviation: "GA",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 100.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 109.99 // Sum of all fees
    },
    {
        stateName: "Hawaii",
        abbreviation: "HI",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 51.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 60.99 // Sum of all fees
    },
    {
        stateName: "Idaho",
        abbreviation: "ID",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 104.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 113.99 // Sum of all fees
    },
    {
        stateName: "Illinois",
        abbreviation: "IL",
        shippingFee: 9.99,
        publishingFee: 102.35,
        stateExpediteFee: 0.00,
        correspondentFee: 153.53,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 265.87 // Sum of all fees
    },
    {
        stateName: "Indiana",
        abbreviation: "IN",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 97.14,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 107.13 // Sum of all fees
    },
    {
        stateName: "Iowa",
        abbreviation: "IA",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 50.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 59.99 // Sum of all fees
    },
    {
        stateName: "Kansas",
        abbreviation: "KS",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 166.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 175.99 // Sum of all fees
    },
    {
        stateName: "Kentucky",
        abbreviation: "KY",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 46.00,
        correspondentFee: 40.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 95.99 // Sum of all fees
    },
    {
        stateName: "Louisiana",
        abbreviation: "LA",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 105.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 114.99 // Sum of all fees
    },
    {
        stateName: "Maine",
        abbreviation: "ME",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 175.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 184.99 // Sum of all fees
    },
    {
        stateName: "Maryland",
        abbreviation: "MD",
        shippingFee: 9.99,
        publishingFee: 50.00,
        stateExpediteFee: 0.00,
        correspondentFee: 46.73,
        proofOfPublication: 100.00,
        recordingFee: 0.00,
        total: 206.72 // Sum of all fees
    },
    {
        stateName: "Massachusetts",
        abbreviation: "MA",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 520.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 529.99 // Sum of all fees
    },
    {
        stateName: "Michigan",
        abbreviation: "MI",
        shippingFee: 9.99,
        publishingFee: 50.00,
        stateExpediteFee: 0.00,
        correspondentFee: 50.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 109.99 // Sum of all fees
    },
    {
        stateName: "Minnesota",
        abbreviation: "MN",
        shippingFee: 9.99,
        publishingFee: 100.00,
        stateExpediteFee: 0.00,
        correspondentFee: 0.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 109.99 // Sum of all fees
    },
    {
        stateName: "Mississippi",
        abbreviation: "MS",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 50.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 59.99 // Sum of all fees
    },
    {
        stateName: "Missouri",
        abbreviation: "MO",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 50.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 59.99 // Sum of all fees
    },
    {
        stateName: "Montana",
        abbreviation: "MT",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 70.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 79.99 // Sum of all fees
    },
    {
        stateName: "Nebraska",
        abbreviation: "NE",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 50.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 59.99 // Sum of all fees
    },
    {
        stateName: "Nevada",
        abbreviation: "NV",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 50.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 59.99 // Sum of all fees
    },
    {
        stateName: "New Hampshire",
        abbreviation: "NH",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 0.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 9.99 // Sum of all fees
    },
    {
        stateName: "New Jersey",
        abbreviation: "NJ",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 35.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 44.99 // Sum of all fees
    },
    {
        stateName: "New Mexico",
        abbreviation: "NM",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 100.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 109.99 // Sum of all fees
    },
    {
        stateName: "New York",
        abbreviation: "NY",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 50.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 59.99 // Sum of all fees
    },
    {
        stateName: "North Carolina",
        abbreviation: "NC",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 100.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 109.99 // Sum of all fees
    },
    {
        stateName: "North Dakota",
        abbreviation: "ND",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 100.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 109.99 // Sum of all fees
    },
    {
        stateName: "Ohio",
        abbreviation: "OH",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 50.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 59.99 // Sum of all fees
    },
    {
        stateName: "Oklahoma",
        abbreviation: "OK",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 50.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 59.99 // Sum of all fees
    },
    {
        stateName: "Oregon",
        abbreviation: "OR",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 50.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 59.99 // Sum of all fees
    },
    {
        stateName: "Pennsylvania",
        abbreviation: "PA",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 0.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 9.99 // Sum of all fees
    },
    {
        stateName: "Rhode Island",
        abbreviation: "RI",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 100.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 109.99 // Sum of all fees
    },
    {
        stateName: "South Carolina",
        abbreviation: "SC",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 100.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 109.99 // Sum of all fees
    },
    {
        stateName: "South Dakota",
        abbreviation: "SD",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 50.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 59.99 // Sum of all fees
    },
    {
        stateName: "Tennessee",
        abbreviation: "TN",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 100.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 109.99 // Sum of all fees
    },
    {
        stateName: "Texas",
        abbreviation: "TX",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 100.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 109.99 // Sum of all fees
    },
    {
        stateName: "Utah",
        abbreviation: "UT",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 50.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 59.99 // Sum of all fees
    },
    {
        stateName: "Vermont",
        abbreviation: "VT",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 100.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 109.99 // Sum of all fees
    },
    {
        stateName: "Virginia",
        abbreviation: "VA",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 100.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 109.99 // Sum of all fees
    },
    {
        stateName: "Washington",
        abbreviation: "WA",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 50.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 59.99 // Sum of all fees
    },
    {
        stateName: "West Virginia",
        abbreviation: "WV",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 100.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 109.99 // Sum of all fees
    },
    {
        stateName: "Wisconsin",
        abbreviation: "WI",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 0.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 9.99 // Sum of all fees
    },
    {
        stateName: "Wyoming",
        abbreviation: "WY",
        shippingFee: 9.99,
        publishingFee: 0.00,
        stateExpediteFee: 0.00,
        correspondentFee: 50.00,
        proofOfPublication: 0.00,
        recordingFee: 0.00,
        total: 59.99 // Sum of all fees
    }
];

export default StateData; 

